### ISSUE TITLE
`GenomicRanges` is not available (for R version 3.4.1) 

### ISSUE THREAD

**Issue by mtwichan** [freestatman/ideogRam#10]
The issue is that the `GenomicRanges` package may be depreciated? I noticed `R (>= 3.3.1)` in the dependencies, and tested out versions `3.31`, `3.41`, and `3.51`.

**Comment by Marlin-Na** [comment]
Hi, thanks for trying out.

The `GenomicRanges` package is a Bioconductor package and is not on CRAN. Instead of using `install.packages`, you may install it with

```r
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicRanges")
```

**Comment by mtwichan** [comment]
Awesome thank you!
